# File: .github/workflows/java_build.yml

name: EchoCore Java Build & Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Diagnostic and Self-Healing Phase ---
      # This step finds the Java source file and stores its path.
      - name: Locate Java Source File
        id: find_source
        run: |
          JAVA_FILE_PATH=$(find . -name "EchoCoreUnifiedFuture.java" -print -quit)
          if [ -z "$JAVA_FILE_PATH" ]; then
            echo "Error: EchoCoreUnifiedFuture.java not found in the repository."
            exit 1
          fi
          echo "Found Java source at: $JAVA_FILE_PATH"
          echo "SOURCE_PATH=$JAVA_FILE_PATH" >> $GITHUB_ENV
          
          # Also, set the directory for classpath
          SOURCE_DIR=$(dirname "$JAVA_FILE_PATH")
          echo "SOURCE_DIR=$SOURCE_DIR" >> $GITHUB_ENV
      # --- End of Diagnostic Phase ---

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Create EchoAI directories
        run: |
          mkdir -p .echoai_future/{plugins,training,logs,fake_includes}

      # Step 4: Compile the Java source code using the discovered path
      - name: Compile EchoCore
        run: javac "$SOURCE_PATH"

      # Step 5: Run the compiled Java application using the discovered path
      - name: Run EchoCoreUnifiedFuture
        run: java -cp "$SOURCE_DIR" EchoCoreUnifiedFuture

      - name: Upload Compiled Code
        uses: actions/upload-artifact@v4
        with:
          name: EchoCore-compiled
          path: "$SOURCE_DIR/*.class"
