name: Live APK Build - EchoCoreCB

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-pip
          pip install buildozer cython kivy

      - name: Create main.py
        run: |
          cat > main.py << 'EOF'
          from kivy.app import App
          from kivy.uix.label import Label
          
          class EchoCoreApp(App):
              def build(self):
                  return Label(text='EchoCoreCB - AGI Mobile Interface Ready')
          
          EchoCoreApp().run()
          EOF

      - name: Initialize Buildozer
        run: buildozer init || true

      - name: Build and package the APK
        run: yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EchoCoreCB-Mobile-AGI
          path: bin/*.apk
          
